### ISSUE TITLE
Test layers

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/platform#101]
I'm sure you guys already have this planned, but it would be super helpful to provide in-memory test layers for the various layers exported by @effect/platform. Maybe having a separate @effect/platform-test module would make sense.

**Comment by tim-smart** [comment]
Yeah eventually, but for the meanwhile, Effect.updateService gets you a long way: https://github.com/Effect-TS/platform/blob/main/packages/platform-node/test/HttpServer.test.ts#L273

**Comment by jessekelly881** [comment]
Oh very cool. I was not aware that that fun existed.
