### ISSUE TITLE
Cloudflare Workers

### ISSUE THREAD

**Issue by nsaunders** [Effect-TS/platform#297]
Hi there, thanks for your work on this project!

I am wondering whether it would be possible to use `@effect/platform` to route requests within a Cloudflare Worker function, i.e. 

> (request: [Request](https://developers.cloudflare.com/workers/runtime-apis/request/)) => Promise<[Response](https://developers.cloudflare.com/workers/runtime-apis/response)>

If so, I would really appreciate if you could please provide a quick example to point me in the right direction.

Thanks in advance for any info, and thanks again for this library!

**Comment by tim-smart** [comment]
Hi! Once #298 is merged it should be possible.
